version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=app_db
    volumes:
      - ./app:/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "--user=root", "--password=$MYSQL_ROOT_PASSWORD", "--execute \"SHOW DATABASES;\""]
      timeout: 20s
      retries: 10

volumes:
  db_data: