version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongodb
      - neo4j
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=app_db
      - MONGO_URL=mongodb://user:pass@mongodb
      - NEO4J_HOST=neo4j
    restart: on-failure
    volumes:
      - ./app:/app
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "--user=root", "--password=$MYSQL_ROOT_PASSWORD", "--execute \"SHOW DATABASES;\""]
      timeout: 20s
      retries: 10
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=tpo
    volumes:
      - mongo_data:/var/lib/mongodb
  neo4j:
    image: neo4j:latest
    container_name: neo4j_db
    ports:
      - "7474:7474"  # HTTP (browser)
      - "7687:7687"  # Bolt (driver)
    environment:
      - NEO4J_AUTH=neo4j/your_password
    volumes:
      - neo4j_data:/var/lib/ne4j/data
volumes:
  db_data:
  mongo_data:
  neo4j_data:
